from enum import Enum

class ErrorHandling(Enum):
   DB_CONNECTION_ERROR = "DATABASE CONNECTION ERROR"
   DB_RETURN_QUERY_ERROR = "DATABASE RETURN QUERY ERROR"
   RETURN_CVS_DATA_ERROR = "ERROR RETURNING CSV DATA"
   RETURN_SQL_DATA_ERROR = "ERROR RETURNING SQL DATA"
   RETURN_EXCEL_DATA_ERROR = "ERROR RETURNING EXCEL DATA"
   RETURN_UNDEFINED_DATA_ERROR = "CANNOT FIND INPUT DATA TYPE"
   SCHEMA_INFO_ERROR = "ERROR IN GET INFO FROM SCHEMA FUNC"
   REMOVE_DUPLICATES_ERROR = "ERROR IN REMOVING DUPLICATES"
   REMOVE_NULLS_ERROR = "ERROR IN REMOVING NULLS FUNC"
   GET_NULLS_ERROR = " ERROR IN GET NULLS FUNC"
   GET_SHAPE_ERROR = "ERROR IN GETTING SHAPE FUNC"
   GET_LENGTH_ERROR = "ERROR IN GETTING LENGTH FUNC"
   CSV_GET_FILES_ERROR= "ERROR IN CVS GET FILES FUNC"

class InputTypes(Enum):
   SQL = "SQL"
   CSV = "CSV"
   EXCEL = "EXCEL"